export const GET_ERRORS = "GET_ERRORS"
export const GET_BOOKS = "GET_BOOKS"
export const GET_BOOK = "GET_BOOK"
export const SET_BOOKLOADING = "SET_BOOKLOADING"
export const DELETE_BOOK = "DELETE_BOOK" 
export const CLEAR_ERRORS = "CLEAR_ERRORS"